### ISSUE TITLE
application crashes whenever i open up a save from the switch version

### ISSUE THREAD

**Issue by Pixel676767** [TollyH/LM2_SaveEditor#1]
I tried to edit a save of the new hd version using the latest version of the save editor but the application just crashed when i tried to open it. How do i fix this?

**Comment by impeeza** [comment]
No to me, I just exported the savegame using JKSV on the Switch copied to my PC, and opened without problem.

My game is in a very eary stage, only A-3, if you don't mind share your save for testing.

**Comment by Pixel676767** [comment]
My save is already finished. I just was hoping to edit it to see if I could match the statistics of my old 3ds version save.

**Comment by impeeza** [comment]
if you don't mind share it to test on my pc

**Comment by TollyH** [comment]
First off, sorry for the inconvenience. As impeeza asked, if possible could you please share a link to a copy of your save file so that I can check it out?

Also, just to rule anything else out, what did you use to obtain your save file? Was it from a physical system or an emulator?

**Comment by Pixel676767** [comment]
It was from an emulator

**Comment by Pixel676767** [comment]
[profile1.txt](https://github.com/user-attachments/files/16045944/profile1.txt)
And here is the file

**Comment by TollyH** [comment]
Thank you! I've found the issue and it should now be fixed (commit 1b071ad4c737603cb5cf5811626fef947925fd8b for reference). I'll upload a patched version soon.

The cause was that the "Last played mansion" selection box was missing an entry for King Boo's Illusion, so if that was the last mansion you played it would be unable to find a matching entry when loading the save file.

**Comment by impeeza** [comment]
Thanks guys for the hard work.

**Comment by HectorLuigiFan** [comment]
Umm where do i need to dowload?
Like what rom i dowloaded from romsfun and i can't open it
